theme: jekyll-theme-minimal
title: SCITAGS
description: Scientific Network Tags Initiative
logo: /assets/img/logo.png
is_project_page: true
is_user_page: false
show_downloads: true
google_analytics: 
