# This is a basic workflow that is manually triggered

name: API generation

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'API sync'
        default: 'World'
        # Input has to be provided for the workflow to run
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.8' 
        architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
    - name: install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - run: python api_gen.py
    - name: commit changes
      uses: EndBug/add-and-commit@v8
      with:
        committer_name: GitHub Actions
        committer_email: actions@github.com
        message: 'Automated API sync'
        add: 'api.json'
